import type { Metadata } from "next";
import { Poppins, Fira_Code, Anton } from "next/font/google";
import "./globals.css";

const geistSans = Poppins({
  variable: "--font-geist-sans",   // mantenemos el nombre, no rompe nada
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const geistMono = Fira_Code({
  variable: "--font-geist-mono",   // idem
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const display = Anton({
  variable: "--font-display",      // para usar en títulos
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${display.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
